// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oevnbmkrtkccxtnxxgas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ldm5ibWtydGtjY3h0bnh4Z2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNDk2OTUsImV4cCI6MjA2NTYyNTY5NX0.EllKQxLXDyzfHC9ucU_QzIuhct_0A7OHfjtAl_WQTlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);